2023-12-05 15:24:23,752 INFO    StreamThr :25860 [internal.py:wandb_internal():86] W&B internal server running at pid: 25860, started at: 2023-12-05 15:24:23.752377
2023-12-05 15:24:23,756 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: status
2023-12-05 15:24:23,761 INFO    WriterThread:25860 [datastore.py:open_for_write():85] open: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\run-zqqqw51o.wandb
2023-12-05 15:24:23,762 DEBUG   SenderThread:25860 [sender.py:send():380] send: header
2023-12-05 15:24:23,764 DEBUG   SenderThread:25860 [sender.py:send():380] send: run
2023-12-05 15:24:24,279 INFO    SenderThread:25860 [dir_watcher.py:__init__():211] watching files in: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files
2023-12-05 15:24:24,279 INFO    SenderThread:25860 [sender.py:_start_run_threads():1124] run started: zqqqw51o with start time 1701786263.752376
2023-12-05 15:24:24,287 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: check_version
2023-12-05 15:24:24,287 DEBUG   SenderThread:25860 [sender.py:send_request():407] send_request: check_version
2023-12-05 15:24:24,350 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: run_start
2023-12-05 15:24:25,762 DEBUG   HandlerThread:25860 [system_info.py:__init__():32] System info init
2023-12-05 15:24:25,762 DEBUG   HandlerThread:25860 [system_info.py:__init__():47] System info init done
2023-12-05 15:24:25,762 INFO    HandlerThread:25860 [system_monitor.py:start():194] Starting system monitor
2023-12-05 15:24:25,762 INFO    SystemMonitor:25860 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-12-05 15:24:25,762 INFO    HandlerThread:25860 [system_monitor.py:probe():214] Collecting system info
2023-12-05 15:24:25,776 INFO    SystemMonitor:25860 [interfaces.py:start():190] Started cpu monitoring
2023-12-05 15:24:25,776 INFO    SystemMonitor:25860 [interfaces.py:start():190] Started disk monitoring
2023-12-05 15:24:25,776 INFO    SystemMonitor:25860 [interfaces.py:start():190] Started gpu monitoring
2023-12-05 15:24:25,776 INFO    SystemMonitor:25860 [interfaces.py:start():190] Started memory monitoring
2023-12-05 15:24:25,786 INFO    SystemMonitor:25860 [interfaces.py:start():190] Started network monitoring
2023-12-05 15:24:25,812 DEBUG   HandlerThread:25860 [system_info.py:probe():196] Probing system
2023-12-05 15:24:25,812 DEBUG   HandlerThread:25860 [gitlib.py:_init_repo():56] git repository is invalid
2023-12-05 15:24:25,812 DEBUG   HandlerThread:25860 [system_info.py:probe():244] Probing system done
2023-12-05 15:24:25,812 DEBUG   HandlerThread:25860 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.10.10', 'heartbeatAt': '2023-12-05T14:24:25.812729', 'startedAt': '2023-12-05T14:24:23.742232', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'c:\\Users\\quint\\Documents\\1. Software Engineer\\AI Edge\\yolov8_person_detector\\main.py', 'codePathLocal': 'main.py', 'codePath': 'main.py', 'host': 'MSI', 'username': 'quint', 'executable': 'C:\\Users\\quint\\miniconda3\\envs\\venv\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2304.0, 'min': 0.0, 'max': 2304.0}, 'cpu_freq_per_core': [{'current': 2304.0, 'min': 0.0, 'max': 2304.0}], 'disk': {'/': {'total': 452.99218368530273, 'used': 432.54737091064453}}, 'gpu': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 15.708507537841797}}
2023-12-05 15:24:25,812 INFO    HandlerThread:25860 [system_monitor.py:probe():224] Finished collecting system info
2023-12-05 15:24:25,812 INFO    HandlerThread:25860 [system_monitor.py:probe():227] Publishing system info
2023-12-05 15:24:25,812 DEBUG   HandlerThread:25860 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-05 15:24:25,816 DEBUG   HandlerThread:25860 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-05 15:24:25,816 DEBUG   HandlerThread:25860 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-12-05 15:24:25,822 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-12-05 15:24:26,296 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\conda-environment.yaml
2023-12-05 15:24:26,296 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\requirements.txt
2023-12-05 15:24:28,366 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:28,366 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:30,929 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:30,929 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:33,454 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:33,454 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:35,982 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:35,983 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:38,535 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:38,535 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:39,089 DEBUG   HandlerThread:25860 [system_info.py:_save_conda():87] Saving conda packages done
2023-12-05 15:24:39,090 INFO    HandlerThread:25860 [system_monitor.py:probe():229] Finished publishing system info
2023-12-05 15:24:39,100 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: status_report
2023-12-05 15:24:39,100 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: keepalive
2023-12-05 15:24:39,100 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: status_report
2023-12-05 15:24:39,100 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: keepalive
2023-12-05 15:24:39,100 DEBUG   SenderThread:25860 [sender.py:send():380] send: files
2023-12-05 15:24:39,100 INFO    SenderThread:25860 [sender.py:_save_file():1380] saving file wandb-metadata.json with policy now
2023-12-05 15:24:39,117 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: stop_status
2023-12-05 15:24:39,118 DEBUG   SenderThread:25860 [sender.py:send_request():407] send_request: stop_status
2023-12-05 15:24:39,120 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: internal_messages
2023-12-05 15:24:39,324 DEBUG   SenderThread:25860 [sender.py:send():380] send: telemetry
2023-12-05 15:24:39,392 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\conda-environment.yaml
2023-12-05 15:24:39,392 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\output.log
2023-12-05 15:24:39,393 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\wandb-metadata.json
2023-12-05 15:24:39,477 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: status_report
2023-12-05 15:24:40,063 INFO    wandb-upload_0:25860 [upload_job.py:push():131] Uploaded file C:\Users\quint\AppData\Local\Temp\tmphb9vn7zbwandb\ajotn54m-wandb-metadata.json
2023-12-05 15:24:41,045 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:41,050 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:41,419 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\output.log
2023-12-05 15:24:43,438 INFO    Thread-16 :25860 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\quint\Documents\1. Software Engineer\AI Edge\yolov8_person_detector\wandb\run-20231205_152423-zqqqw51o\files\output.log
2023-12-05 15:24:43,564 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:43,565 ERROR   gpu       :25860 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2023-12-05 15:24:43,893 INFO    memory    :25860 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2023-12-05 15:24:43,893 INFO    cpu       :25860 [interfaces.py:monitor():140] Process cpu has exited.
2023-12-05 15:24:43,932 DEBUG   SystemMonitor:25860 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-12-05 15:24:43,932 DEBUG   SystemMonitor:25860 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2023-12-05 15:24:43,932 DEBUG   SystemMonitor:25860 [system_monitor.py:_start():183] Publishing last batch of metrics
2023-12-05 15:24:43,932 DEBUG   SenderThread:25860 [sender.py:send():380] send: stats
2023-12-05 15:24:44,650 INFO    MainThread:25860 [internal.py:handle_exit():76] Internal process exited
2023-12-05 15:24:45,046 DEBUG   HandlerThread:25860 [handler.py:handle_request():146] handle_request: status_report
